spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:todo
    username: user
    password:
    driverClassName: org.h2.Driver

springdoc:
  paths-to-match: /api/v1/**/